name = "Registrator"
uuid = "4418983a-e44d-11e8-3aec-9789530b3b3e"
authors = ["Stefan Karpinski <stefan@karpinski.org>"]
version = "1.9.4"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
GitForge = "8f6bce27-0656-5410-875b-07a5572985df"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
RegistryTools = "d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TimeToLive = "37f0c46e-897f-50ef-b453-b26c3eed3d6c"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
AutoHashEquals = "0.2"
Base64 = "1"
Dates = "1"
Distributed = "1"
FileWatching = "1"
GitForge = "0.4.0"
GitHub = "5.7.0"
HTTP = "0.8, 0.9, 1"
JSON = "0.20, 0.21"
LibGit2 = "1"
Logging = "1"
MbedTLS = "0.6.8, 0.7, 1"
Mocking = "0.7"
Mustache = "0.5, 1.0"
Mux = "0.7, 1"
Pkg = "1"
RegistryTools = "2"
Serialization = "1"
Sockets = "1"
TimeToLive = "0.2, 0.3"
URIs = "1"
UUIDs = "1"
ZMQ = "1"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
