# See README.web.md for details on each key.

[web]
ip = ""
port = 8003
server_url = ""
registry_url = ""
stop_file = "/tmp/stopwebui"
log_level = "DEBUG"
registry_clone_url = ""
# extra_providers = ""
# registry_provider = ""
registry_deps = []
# disable_release_notes = false
route_prefix = "/registrator/web"
# backend_port = 5555

[web.github]
token = ""
client_id = ""
client_secret = ""
# api_url = ""
# auth_url = ""
# token_url = ""
# disable_rate_limits = false

[web.gitlab]
token = ""
client_id = ""
client_secret = ""
# api_url = ""
# auth_url = ""
# token_url = ""
# disable_rate_limits = false
